blog_site/accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_page, name='register' ),
]

blog_site/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index,name='index'),
    path('<int:article_id>/', views.detail ,name='detail'),
    path('<int:article_id>/leave_coment', views.leave_coment ,name='leave_coment'),
    path('<int:comment_id>/delete_comment', views.delete_comment ,name='delete_comment'),
    path('new_article', views.add_article,name='add_article'),
    path('<int:article_id>/delete', views.delete_article ,name='delete_article'),
    path('<int:article_id>/update', views.update_article ,name='update_article'),
]

blog_site/blog_site/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('articles/',include('articles.urls')),
    path('accounts/', include('accounts.urls'))
]

blog_site/accounts/models.py
from django.db import models

# Create your models here.

blog_site/articles/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, verbose_name="Article title", unique=True, default='')
    text = models.TextField(verbose_name='Article text', default='')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.title)
    
    def get_cut_text(self):
        return f'{str(self.text)[:70]}...'

    class Meta:
        managed = True
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'
 

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200, verbose_name='Comment text', default='')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.text

    class Meta:
        verbose_name = 'Coment'
        verbose_name_plural = 'Coments'

blog_site/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(
    attrs={'class':'form-control form-control-lg','type':'password', 'name': 'password1','placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(
    attrs={'class':'form-control form-control-lg','type':'password', 'name': 'password2','placeholder':'Password confirmation'}))

    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        widgets = {
            'username' : forms.TextInput(
                attrs={
                    'class': 'form-control form-control-lg',
                    'placeholder':'Username'
                }
            ),
            'email' : forms.EmailInput(
                attrs={
                    'class': 'form-control form-control-lg',
                    'placeholder':'Email'
                }
            ),
        }

blog_site/articles/forms.py
from articles.models import Article
from django import forms

class AddArticleForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control form-control-lg',
            'type':'text', 
            'name': 'title',
            'placeholder':'Enter the title'
            }))

    text = forms.CharField(widget=forms.Textarea(
        attrs=
        {
            'class':'form-control form-control-lg',
            'placeholder':'Enter the text of article'
            }))
    
    class Meta:
        model = Article
        fields = ['title','text',]
       

blog_site/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

def login_page(request):

    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            response = redirect('/articles/')
            return response
        else:
            messages.info(request, 'Username or password is incorrect')

    return render(request, 'accounts/login.html')

def logout_user(request):
    logout(request)
    response = redirect('/articles/')
    return response


def register_page(request):
    form = CreateUserForm()
    if request.POST:
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()

            username = request.POST.get('username')
            password = request.POST.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)
                
            response = redirect('/articles/')
            return response

    context = {'form':form}
    return render(request, 'accounts/register.html',context)

blog_site/articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, Http404
from .models import Article, Comment
from django.urls import reverse
from .forms import AddArticleForm
from django.contrib import messages

def index(request):
    articles = Article.objects.all().order_by('-date')
    for article in articles:
        article.text = article.get_cut_text()
    content = {
        'articles':articles,
    }
    return render(request, 'articles/list.html', content)


def detail(request, article_id):
    try:
        article = Article.objects.get(id=article_id)
    except:
        raise Http404('No page')

    comments = article.comment_set.all().order_by('-date')
    content = {
        'article':article ,
        'comments':comments,
    }

    return render(request, 'articles/article.html', content)


def leave_coment(request, article_id):
    try:
        if request.POST:
            article = Article.objects.get(id=article_id)
            content = {
                'article':article ,
        }
    except:
        raise Http404('No page')
    article.comment_set.create(author=request.user, text=request.POST['text'])

    return redirect(f'/articles/{article_id}')

def delete_comment(request, comment_id):
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect(f'/articles/{comment.article.id}')

def add_article(request):
    if request.POST:
        form = AddArticleForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            response = redirect('/articles/')
            return response
    else:
        form = AddArticleForm()

    context = {
        'form' : form,
    }
    return render(request, 'articles/new_article.html',context)

def delete_article(request, article_id):
    article = Article.objects.get(id=article_id)
    article.delete()
    return redirect('/articles/')

def update_article(request, article_id):
    article = Article.objects.get(id=article_id)
    form = AddArticleForm(instance=article)

    if request.POST:
        form = AddArticleForm(request.POST, instance=article)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            response = redirect('/articles/')
            return response


    context = {
        'form' : form,
        'article' :article,
    }
    return render(request, 'articles/update_article.html',context)

blog_site/accounts/templates/accounts/login.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<section class="vh-100 bg-image" style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.jpg');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Login into system</h2>

                <form action="{% url 'accounts:login' %}" class="form" method="POST">
                    {% csrf_token %}

                    <div class="form-outline mb-4">
                        <input type="text" name="username" class="form-control form-control-lg" placeholder="Username">
                    </div>
                    <div class="form-outline mb-4">
                        <input type="password" name="password" class="form-control form-control-lg" placeholder="Password">
                    </div>
                    
                    
                    {% if messages %}
                        {% for message in messages %}
                            <p id="messages">{{message}}</p>
                        {% endfor %}
                    {% endif %}

                    <div class="form-check d-flex justify-content-center mb-5">

                    </div>

                    <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Login</button>
                    </div>

                    <p class="text-center text-muted mt-5 mb-0">Don't have an account? <a href="{% url 'accounts:register' %}" class="fw-bold text-body"><u>Sign up</u></a></p>

                </form>

                

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

blog_site/accounts/templates/accounts/register.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<section class="vh-100 bg-image" style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.jpg');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

                <form action="{% url 'accounts:register' %}" class="form" method="POST">
                    {% csrf_token %}
                    {% for field in form  %}
                        <div class="form-outline mb-4">
                            {{field}}
                            
                        </div>
                    {% endfor %}

                    <div class="form-check d-flex justify-content-center mb-5">

                    </div>

                    <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                    </div>


                </form>
                {{form.errors}}
                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="{% url 'accounts:login' %}" class="fw-bold text-body"><u>Login here</u></a></p>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

blog_site/articles/templates/articles/article.html
{% extends 'base.html' %} 

{% block title %}{{ article.title }}{% endblock %} 



{% block content %} 
    <div class="container p-5">
        <div class="container p-5">
            <h3>{{article.title}}</h3>
            {{article.text}}
            <br>
            <div class="container pt-5">
                <form action="{% url 'articles:leave_coment' article.id %}" class="form" method="POST">

                    {% csrf_token %}
                        <textarea class="form-control form-control-lg" name="text" required="" placeholder="Leave your coment" cols="15" rows="5"></textarea><br>

                    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="submit" class="d-flex btn btn-primary justify-content-end">Leave comment</button>
                    </div>
                </form>
                {% for comment in comments%}
                    <div class="d-flex justify-content-between m-3">
                        <div class="container">
                        <strong>{{comment.author}}:</strong>  {{comment.text}} 
                        <em>{{comment.date}}</em>
                        <br>
                        </div>
                        {% if request.user.is_authenticated %} 
                            {% if request.user == comment.author %}
                            <div class="ms-3">
                                <a href="{% url 'articles:delete_comment' comment.id %}" class="text-decoration-none link-dark">
                                    <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="25"
                                    height="25"
                                    fill="currentColor"
                                    class="bi bi-trash"
                                    viewBox="0 0 16 16"
                                    >
                                    <path
                                        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
                                    />
                                    <path
                                        fill-rule="evenodd"
                                        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                                    />
                                    </svg>
                                </a>
                            </div>
                            {% endif %}
                        {% endif %}
                        
                    </div>
                {% endfor %}
            </div>
        </div>
          
        
    </div>
    
{% endblock %}

blog_site/articles/templates/articles/list.html
{% extends 'base.html' %} 
{% block title %}Last articles{% endblock %} 
{% block content %} 
{% if articles %}

<div class="container p-5 ">
{% for article in articles %}
    <div class="col mt-2">
      <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 ">
        <div  class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">{{ article.author }}</strong>
          <a href="{% url 'articles:detail' article.id %}" style="position: relative" class="text-decoration-none link-dark stretched-link">
          <h3 class="mb-0">{{ article.title }}</h3>
          </a>
          <div class="mb-1 text-muted">{{ article.date }}</div>
          <p class="mb-auto">{{ article.text }}</p>
          
        </div>
        {% if request.user.is_authenticated %} 
            {% if request.user == article.author %}
            <div class="col-auto d-none d-lg-block m-3">
                <a href="{% url 'articles:update_article' article.id %}" class="m-2 text-decoration-none link-dark">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="26"
                    height="26"
                    fill="currentColor"
                    class="bi bi-pen"
                    viewBox="0 0 16 16"
                    >
                    
                    <path
                        d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"
                    />
                    </svg>
                </a>
                <a href="{% url 'articles:delete_article' article.id %}" class="text-decoration-none link-dark">
                    <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="26"
                    height="26"
                    fill="currentColor"
                    class="bi bi-trash"
                    viewBox="0 0 16 16"
                    >
                    <path
                        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
                    />
                    <path
                        fill-rule="evenodd"
                        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                    />
                    </svg>
                </a>
            </div>
            {% endif %}
        {% endif %}
      </div>
    </div>
{% endfor %}
</div>


{% else %}
<div class="container">
  <p class="text-center fs-2 my-5">Be the first!!!</p>

  {% if not request.user.is_authenticated %}
  <div class="d-grid gap-2 d-md-flex justify-content-md-center">
    <a class="btn btn-primary me-2 w-25" href="{% url 'accounts:register'%}"
      >Sign Up</a
    >
    <a class="btn btn-success w-25" href="{% url 'accounts:login'%}">Login</a>
  </div>
  {% endif %}
</div>

{% endif %} 


{% endblock %}

blog_site/articles/templates/articles/new_article.html
{% extends 'base.html' %} 
{% block title %}Add article{% endblock %} 
{% block content %} 


<div class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">Add new article</h6>

        <form action="{% url 'articles:add_article' %}" class="form" method="POST">
            {% csrf_token %}
            
            {% for field in form%}
                <div class="mb-3">
                     {{field}}
                </div>
                   
                
            {% endfor %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-success">Add</button>
            </div>
        </form>

    </div>
</div>
 


{% endblock %}

blog_site/articles/templates/articles/update_article.html
{% extends 'base.html' %} 
{% block title %}Update article{% endblock %} 
{% block content %} 


<div class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <h6 class="border-bottom pb-2 mb-0">Update article</h6>

        <form action="{% url 'articles:update_article' article.id %}" class="form" method="POST">
            {% csrf_token %}
            
            {% for field in form%}
                <div class="mb-3">
                     {{field}}
                </div>
                   
                
            {% endfor %}
            {{form.errors}}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </form>


    </div>
</div>
 


{% endblock %}

blog_site/articles/templates/base.html
<!DOCTYPE html>

{% comment %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'haudi/css/bootstrap.css' %}"/> {% endcomment %}

{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}My blog {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark  p-0 ">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'articles:index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0"></ul>

          {% if not request.user.is_authenticated %}
              <span class="navbar-text">
                <a class="nav-link" href="{% url 'accounts:register' %}" >Sign Up</a>
              </span>
              <span class="navbar-text">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </span>

          {% else %}
            <a class="nav-link" href="{% url 'articles:add_article' %}" tabindex="-1">
              <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="white" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
              </svg>
            </a>
            <span class="navbar-text">
              <a class="nav-link" href="{% url 'accounts:logout' %}" tabindex="-1">Logout from {{request.user}}</a>
            </span>
          {% endif %}

          {% comment %} <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> {% endcomment %}
        </div>
      </div>
    </nav>
    
    {% block content %}{% endblock %}
    
  </body>
</html>